version: '3.8'

services:
  postgres:
    image: postgres:14

  migrations:
    build:
      dockerfile: libs/db/Dockerfile
      context: .
    image: mathpaquette/tskmgr-migrations:${TSKMGR_VERSION:-latest}
    environment:
      DB_HOST: 'localhost'
      DB_PORT: 5432
      DB_USERNAME: 'tskmgr'
      DB_PASSWORD: 'tskmgr'
      DB_DATABASE: 'tskmgr'
    depends_on:
      - postgres

  api:
    build:
      dockerfile: apps/api/Dockerfile
      context: .
    image: mathpaquette/tskmgr-api:${TSKMGR_VERSION:-latest}
    environment:
      DB_HOST: 'localhost'
      DB_PORT: 5432
      DB_USERNAME: 'tskmgr'
      DB_PASSWORD: 'tskmgr'
      DB_DATABASE: 'tskmgr'
    volumes:
      - ./data/api/files:/app/files
    ports:
      - "3333:3333"
    depends_on:
      - migrations

  frontend:
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
    image: mathpaquette/tskmgr-frontend:${TSKMGR_VERSION:-latest}
    environment:
      PORT: 8080
      API_URL: 'http://api:3333'
    ports:
      - "8080:8080"
    depends_on:
      - api
