version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'tskmgr', '-U', 'tskmgr']
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: mathpaquette/tskmgr-migrations:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: mathpaquette/tskmgr-api:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    volumes:
      - ./data/api/files:/app/files
    ports:
      - '3333:3333'
    depends_on:
      - migrations

  frontend:
    image: mathpaquette/tskmgr-frontend:latest
    environment:
      PORT: ${FRONTEND_PORT}
      API_URL: ${API_URL}
    ports:
      - '8080:8080'
    depends_on:
      - api
