version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: tskmgr
      POSTGRES_PASSWORD: tskmgr
      POSTGRES_DB: tskmgr
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'tskmgr', '-U', 'tskmgr']
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: mathpaquette/tskmgr-migrations:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: tskmgr
      DB_PASSWORD: tskmgr
      DB_DATABASE: tskmgr
    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: mathpaquette/tskmgr-api:latest
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: tskmgr
      DB_PASSWORD: tskmgr
      DB_DATABASE: tskmgr
    volumes:
      - ./data/api/files:/app/files
    ports:
      - 3333:3333
    depends_on:
      - migrations

  frontend:
    image: mathpaquette/tskmgr-frontend:latest
    environment:
      PORT: 8080
      API_URL: 'http://api:3333'
    ports:
      - 8080:8080
    depends_on:
      - api
